# hive-backend is a role intended to enable groups running hive to have
# debug access when investigating issues (whether the issue is with
# hive or with the cluster(s) being managed).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hive-backend
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - list
  - watch
