apiVersion: v1
kind: Template
metadata:
  name: hive-deployment

parameters:
  - name: DEPLOY_IMAGE
    displayName: Deploy image
    description: container image with hive components.
    value: registry.svc.ci.openshift.org/openshift/hive-v4.0:hive
  - name: HIVE_NS
    displayName: Hive Namespace
    description: Namespace where core hive components will run.
    value: hive
  - name: LOG_LEVEL
    displayName: Log level
    value: info

objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: hive-operator
      namespace: ${HIVE_NS}

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: hive-operator-role
    rules:
    - apiGroups:
      - hive.openshift.io
      resources:
      - '*'
      verbs:
      - '*'
    - apiGroups:
      - hiveinternal.openshift.io
      resources:
      - '*'
      verbs:
      - '*'
    - apiGroups:
      - velero.io
      resources:
      - backups
      verbs:
      - create
    - apiGroups:
      - ""
      resources:
      - serviceaccounts
      - serviceaccounts/finalizers
      - secrets
      - secrets/finalizers
      - services
      - services/finalizers
      - events
      - configmaps
      - namespaces
      - persistentvolumeclaims
      verbs:
      - '*'
    - apiGroups:
      - apiregistration.k8s.io
      resources:
      - apiservices
      - apiservices/finalizers
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - admissionregistration.k8s.io
      resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - apps
      resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - daemonsets/finalizers
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - apps.openshift.io
      resources:
      - deploymentconfigs
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - authorization.openshift.io
      resources:
      - clusterroles
      - clusterrolebindings
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - batch
      resources:
      - jobs
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - ""
      resources:
      - pods
      - pods/log
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - admission.hive.openshift.io
      resources:
      - dnszones
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - authorization.k8s.io
      resources:
      - subjectaccessreviews
      verbs:
      - create
    - apiGroups:
      - admission.hive.openshift.io
      resources:
      - clusterdeployments
      - clusterimagesets
      - clusterprovisions
      - dnszones
      - machinepools
      - selectorsyncsets
      - syncsets
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: hive-operator-rolebinding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: hive-operator-role
    subjects:
    - kind: ServiceAccount
      name: hive-operator
      namespace: ${HIVE_NS}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        control-plane: hive-operator
        controller-tools.k8s.io: "1.0"
      name: hive-operator
      namespace: ${HIVE_NS}
    spec:
      replicas: 1
      revisionHistoryLimit: 4
      selector:
        matchLabels:
          control-plane: hive-operator
          controller-tools.k8s.io: "1.0"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            control-plane: hive-operator
            controller-tools.k8s.io: "1.0"
        spec:
          containers:
          - command:
            - /opt/services/hive-operator
            - --log-level
            - ${LOG_LEVEL}
            env:
            - name: CLI_CACHE_DIR
              value: /var/cache/kubectl
            - name: HIVE_OPERATOR_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            image: ${DEPLOY_IMAGE}
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
            name: hive-operator
            readinessProbe:
              httpGet:
                path: /readyz
                port: 8080
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - mountPath: /var/cache/kubectl
              name: kubectl-cache
          serviceAccountName: hive-operator
          terminationGracePeriodSeconds: 10
          volumes:
          - emptyDir: {}
            name: kubectl-cache
